version: '2'
services:
  zookeeper:
    image: stratio/zookeeper:3.4.6
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  schema-registry:
      image: confluentinc/cp-schema-registry:3.1.0
      network_mode: host
      depends_on:
       - zookeeper
      environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:2181

  kafka:
    image: confluentinc/cp-kafka:3.1.0
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  khermes-seed:
    image: qa.stratio.com/hermes/hermes:0.2.0-SNAPSHOT
    network_mode: host
    depends_on:
      - kafka
    environment:
      SEED: "true"
      SEED_PORT: 2552
      ZK_PORT: 2181